name: Filter European files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Install rust
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: compile
        run: cargo build --release

      - name: download filter for all
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/catenarytransit/pfaedled-gtfs-actions/refs/heads/main/pfaedle-filter-all.txt
        
      - name: Download OSM file Deutschland
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/europe/germany-latest.osm.pbf

      - name: Filter Deutschland
        run: osmium tags-filter -o pfaedle-filtered-germany-latest.osm.pbf --expressions=pfaedle-filter-all.txt germany-latest.osm.pbf

      - name: Delete old deutschland file
        run: rm germany-latest.osm.pbf
        
      - name: Filter deutschland road names out
        run: |
          ./target/release/osm-filter  pfaedle-filtered-germany-latest.osm.pbf  pfaedle-filtered-germany-latest-temp.osm.pbf
          mv pfaedle-filtered-germany-latest-temp.osm.pbf  pfaedle-filtered-germany-latest.osm.pbf

      - name: Upload filtered file
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pfaedle-filtered-germany-latest.osm.pbf 
          ASSET_NAME: pfaedle-filtered-germany-latest.osm.pbf 
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Delete old deutschland files
        run: rm pfaedle-filtered-germany-latest.osm.pbf
