name: Filter European files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: download filter for all
        run: wget https://github.com/catenarytransit/pfaedled-gtfs-actions/blob/main/pfaedle-filter-all.txt

      - name: Download OSM files
        run: wget https://download.geofabrik.de/europe/germany-latest.osm.pbf

      - name: Filter Deutschland
        run: osmium tags-filter -o pfaedle-filtered-germany-latest.osm.pbf --expressions=pfaedle-filter-all.txt germany-latest.osm.pbf

      - name: Upload filtered file
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pfaedle-filtered-germany-latest.osm.pbf 
          ASSET_NAME: pfaedle-filtered-germany-latest.osm.pbf 
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
