name: Filter European files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Install rust
        run: rustup toolchain install stable

      - name: compile
        run: cargo build --release

      - name: download filter for all
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/catenarytransit/pfaedled-gtfs-actions/refs/heads/main/pfaedle-filter-all.txt
        
      - name: Download OSM file Deutschland
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/europe/germany-latest.osm.pbf

      - name: Filter Deutschland
        run: osmium tags-filter -o pfaedle-filtered-germany-latest.osm.pbf --expressions=pfaedle-filter-all.txt germany-latest.osm.pbf

      - name: Delete old deutschland file
        run: rm germany-latest.osm.pbf
        
      - name: Filter deutschland road names out
        run: |
          ./target/release/osm-filter  pfaedle-filtered-germany-latest.osm.pbf  pfaedle-filtered-germany-latest-temp.osm.pbf
          mv pfaedle-filtered-germany-latest-temp.osm.pbf  pfaedle-filtered-germany-latest.osm.pbf

      - name: Upload filtered file Deutschland
        env: 
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pfaedle-filtered-germany-latest.osm.pbf 
          ASSET_NAME: pfaedle-filtered-germany-latest.osm.pbf 
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Delete old deutschland files
        run: rm pfaedle-filtered-germany-latest.osm.pbf

      - name: Download OSM file Sweden
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/europe/sweden-latest.osm.pbf

      - name: Filter Sweden
        run:  osmium tags-filter -o pfaedle-filtered-sweden-latest.osm.pbf --expressions=pfaedle-filter-all.txt sweden-latest.osm.pbf

      - name: Upload filtered file Sweden
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pfaedle-filtered-sweden-latest.osm.pbf
          ASSET_NAME: pfaedle-filtered-sweden-latest.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Delete old sweden file
        run: rm sweden-latest.osm.pbf

      - name: download file for British Isles
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/europe/britain-and-ireland-latest.osm.pbf

      - name: Filter Ireland for Rail CRS
        run: osmium tags-filter -o crs-networkrail.osm.pbf --expressions=crsfilter.txt britain-and-ireland-latest.osm.pbf

      - name: Upload filtered file Rail CRS
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: crs-networkrail.osm.pbf
          ASSET_NAME: crs-networkrail.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
