name: Filter australia-oceaniaese files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: APT Update
        run: sudo apt update

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Install rust
        run: rustup toolchain install stable

      - name: "Download Oceania"
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/australia-oceania-latest.osm.pbf

      - name: Filter australia-oceania for railways
        run: osmium tags-filter -o railway-filtered-australia-oceania-latest.osm.pbf --expressions=railway-filter.txt australia-oceania-latest.osm.pbf

      - name: Filter australia-oceania for railway stations
        run: osmium tags-filter -o railstations-australia-oceania-latest.osm.pbf --expressions=railway-station-filter.txt australia-oceania-latest.osm.pbf

      - name: "Upload australia-oceania filtered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: railway-filtered-australia-oceania-latest.osm.pbf
          ASSET_NAME: railway-filtered-australia-oceania-latest.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: "Upload australia-oceania stations filtered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: railstations-australia-oceania-latest.osm.pbf
          ASSET_NAME: railstations-australia-oceania-latest.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
